//! Module containing several parameters used across the codebase
//!
//! These parameter can be either constants or configurable via environment variables
//! but they are not expected to change during runtime.
//! For retrieving parameters that can be configured during startup (with env variables),
//! see the [`load_configurables_from_env`] function and the [`configurables`] accessor.

/// Defines the name of the index timestamp column in the arrow schema
pub const ARROW_SCHEMA_COLUMN_NAME_INDEX_TIMESTAMP: &str = "timestamp_ns";

/// Defines schema name for mosaico resources
pub const MOSAICO_URL_SCHEMA: &str = "mosaico";

/// Internal resolution for floating point comparisons
pub const EPSILON: f64 = 1.0e-06;

/// Name of the default layer
pub const DEFAULT_LAYER_NAME: &str = "default";
pub const DEFAULT_LAYER_DESCRIPTION: &str =
    "Default layer, this layer is automatically generated by mosaico at startup";

/// Module containing several file extensions
pub mod ext {
    /// Json file extension
    pub const JSON: &str = "json";
    pub const PARQUET: &str = "parquet";
}

use std::{env, str::FromStr, sync::OnceLock};

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("unable to parse variable `{0}`")]
    UnableToParse(String),
    #[error("unable to retrieve variable `{0}`, error: {1}")]
    RetrieveError(String, String),
}

/// Required and configurables parameters of mosaico
#[derive(Debug)]
pub struct Params {
    pub max_message_size_in_bytes: usize,
    pub target_message_size_in_bytes: usize,
    /// Maximum number of concurrent chunk queries during data catalog filtering
    pub max_concurrent_chunk_queries: usize,
    /// Maximum number of database connections in the pool
    pub max_db_connections: u32,
    /// Maximum chunk size in bytes before automatic splitting during upload.
    /// When a chunk exceeds this size, it is finalized and a new chunk is started.
    /// A value of 0 means unlimited (no automatic splitting).
    pub max_chunk_size_in_bytes: usize,

    /// Path of the `cert.pem` file used as TLS certificate
    pub tls_certificate_file: String,
    /// Path of the `key.pem` file used as private key for TLS
    pub tls_private_key_file: String,

    pub db_url: String,

    pub store_endpoint: String,
    pub store_bucket: String,
    pub store_secret_key: Hidden,
    pub store_access_key: String,
}

pub fn load_params_from_env() -> Result<(), Error> {
    let ev = Params {
        // buffering
        max_message_size_in_bytes: optional(
            "MOSAICOD_MAX_MESSAGE_SIZE_IN_BYTES",
            (50 * 1024 * 1024) as usize,
        ),
        target_message_size_in_bytes: optional(
            "MOSAICOD_TARGET_MESSAGE_SIZE_IN_BYTES",
            25 * 1024 * 1024,
        ),
        max_concurrent_chunk_queries: optional("MOSAICOD_MAX_CONCURRENT_CHUNK_QUERIES", 4),
        max_db_connections: optional("MOSAICOD_MAX_DB_CONNECTIONS", 10),
        max_chunk_size_in_bytes: optional(
            "MOSAICOD_MAX_CHUNK_SIZE_IN_BYTES",
            256 * 1024 * 1024, // 256 MiB default
        ),

        // tls
        tls_certificate_file: optional("MOSAICOD_TLS_CERT_FILE", "".to_owned()),
        tls_private_key_file: optional("MOSAICOD_TLS_PRIVATE_KEY_FILE", "".to_owned()),

        // database
        db_url: required("MOSAICOD_DB_URL")?,

        // store
        store_endpoint: optional("MOSAICOD_STORE_ENDPOINT", "".to_owned()),
        store_bucket: optional("MOSAICOD_STORE_BUCKET", "".to_owned()),
        store_secret_key: Hidden::from(optional("MOSAICOD_STORE_SECRET_KEY", "".to_owned())),
        store_access_key: optional("MOSAICOD_STORE_ACCESS_KEY", "".to_owned()),
    };

    let _ = ENV.set(ev);

    Ok(())
}

static ENV: OnceLock<Params> = OnceLock::new();

pub fn params() -> &'static Params {
    ENV.get().expect("paramenters not initialized, plase call `params::load_configurables_from_env()` before accessing an env variable.")
}

fn optional<T>(name: &str, default: T) -> T
where
    T: std::str::FromStr,
    <T as FromStr>::Err: std::fmt::Debug,
{
    match env::var(name) {
        Ok(value) => value
            .parse()
            .unwrap_or_else(|_| panic!("unable to parse variable `{}`", name)),
        Err(_) => default,
    }
}

fn required<T>(name: &str) -> Result<T, Error>
where
    T: std::str::FromStr,
    <T as FromStr>::Err: std::fmt::Debug,
{
    let value = env::var(name).map_err(|e| Error::RetrieveError(name.into(), e.to_string()))?;

    let t = value
        .parse()
        .map_err(|_| Error::UnableToParse(name.into()))?;

    Ok(t)
}

/// This staruct is used to hold sensitive information that should not be
/// printed in logs or debug output.
#[derive(Clone)]
pub struct Hidden(String);

impl Hidden {
    pub fn get(&self) -> &String {
        &self.0
    }

    pub fn take(self) -> String {
        self.0
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl From<String> for Hidden {
    fn from(value: String) -> Self {
        Self(value)
    }
}

impl std::fmt::Debug for Hidden {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "**********")
    }
}

impl std::fmt::Display for Hidden {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "**********")
    }
}

/// Returns mosaicod version.
pub fn get_version() -> String {
    let mut version = env!("CARGO_PKG_VERSION").to_owned();
    if cfg!(debug_assertions) {
        version.push_str("-devel");
    }
    version
}
