from dataclasses import dataclass
from typing import Any, Dict


@dataclass
class TimestampRange:
    """
    Represents a temporal window defined by a start and end timestamp.

    This utility class is used to define the bounds of sensor data or sequences
    within the Mosaico archive.

    Attributes:
        start (int): The beginning of the range (inclusive), typically in nanoseconds.
        end (int): The end of the range (inclusive), typically in nanoseconds.
    """

    start: int
    end: int

    @classmethod
    def _from_dict(cls, data: Dict[str, Any]) -> "TimestampRange":
        return cls(start=data["start_ns"], end=data["end_ns"])

    def to_dict(self):
        return {
            "start_ns": self.start,
            "end_ns": self.end,
        }


@dataclass
class TopicCluster:
    """
    A `TopicCluster` object represents a time interval where something relevant happened.
    These are typically generated by asking the backend Topic Filter Clusterize or Topic Filter Intersect actions.

    Attributes:
        id: The cluster index if multiple clustyers are returned for the same topic.
        timerange: The interval that the cluster identifies.
    """

    id: int
    timerange: TimestampRange

    @classmethod
    def _from_dict(cls, data: Dict[str, Any]) -> "TopicCluster":
        """
        Creates a TopicCluster object from a dictionary.

        Args:
            data: The dictionary to create the TopicCluster object from.

        Returns:
            A TopicCluster object.
        """

        return cls(
            id=data["id"],
            timerange=TimestampRange._from_dict(data["ts"]),
        )

    def __str__(self) -> str:
        return f"(id={self.id}, start={self.timerange.start}, end={self.timerange.end})"
