from dataclasses import dataclass
from typing import Any, Dict

from .response import TimestampRange


@dataclass
class TopicCluster:
    """
    Platform topic cluster.

    A `TopicCluster` object represents a time interval where something relevant happened.
    These are typically generated by asking the backend Clusterize or Intersect actions.

    Attributes:
        id: The unique identifier of the cluster.
        timerange: The interval that the cluster identifies.
    """

    id: int
    timerange: TimestampRange

    @classmethod
    def _from_dict(cls, data: Dict[str, Any]) -> "TopicCluster":
        """
        Creates a TopicCluster object from a dictionary.

        Args:
            data: The dictionary to create the TopicCluster object from.

        Returns:
            A TopicCluster object.
        """

        return cls(
            id=data["id"],
            timerange=TimestampRange._from_dict(data["timerange"]),
        )
