# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mosaicod/v1/core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16mosaicod/v1/core.proto\x12\x10mosaicod.v1.core\"\x07\n\x05\x45mpty*Y\n\x06\x46ormat\x12\x16\n\x12\x46ORMAT_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x46ORMAT_DEFAULT\x10\x01\x12\x11\n\rFORMAT_RAGGED\x10\x02\x12\x10\n\x0c\x46ORMAT_IMAGE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mosaicod.v1.core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FORMAT._serialized_start=53
  _FORMAT._serialized_end=142
  _EMPTY._serialized_start=44
  _EMPTY._serialized_end=51
# @@protoc_insertion_point(module_scope)
