# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mosaicod/v1/requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mosaicolabs.proto.v1 import core_pb2 as mosaicod_dot_v1_dot_core__pb2
from mosaicolabs.proto.v1 import time_pb2 as mosaicod_dot_v1_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amosaicod/v1/requests.proto\x12\x14mosaicod.v1.requests\x1a\x16mosaicod/v1/core.proto\x1a\x16mosaicod/v1/time.proto\"\"\n\x0fResourceLocator\x12\x0f\n\x07locator\x18\x01 \x01(\t\"#\n\x0bSessionUuid\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\"M\n\x12NotificationCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x19\n\x11notification_type\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"8\n\x0eSequenceCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x15\n\ruser_metadata\x18\x02 \x01(\x0c\"\x99\x01\n\x0bTopicCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x14\n\x0csession_uuid\x18\x02 \x01(\t\x12\x36\n\x14serialization_format\x18\x03 \x01(\x0e\x32\x18.mosaicod.v1.core.Format\x12\x14\n\x0contology_tag\x18\x04 \x01(\t\x12\x15\n\ruser_metadata\x18\x05 \x01(\x0c\"\x8f\x01\n\x15TopicClusterizeParams\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x18\n\x10\x63lustering_dt_ns\x18\x02 \x01(\x04\x12\x10\n\x08ontology\x18\x03 \x01(\x0c\x12\x39\n\x0ftimestamp_range\x18\x04 \x01(\x0b\x32 .mosaicod.v1.time.TimestampRange\"l\n\x14TopicFilterIntersect\x12;\n\x06topics\x18\x01 \x03(\x0b\x32+.mosaicod.v1.requests.TopicClusterizeParams\x12\x17\n\x0fintersect_dt_ns\x18\x02 \x01(\x04\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mosaicod.v1.requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCELOCATOR._serialized_start=100
  _RESOURCELOCATOR._serialized_end=134
  _SESSIONUUID._serialized_start=136
  _SESSIONUUID._serialized_end=171
  _NOTIFICATIONCREATE._serialized_start=173
  _NOTIFICATIONCREATE._serialized_end=250
  _SEQUENCECREATE._serialized_start=252
  _SEQUENCECREATE._serialized_end=308
  _TOPICCREATE._serialized_start=311
  _TOPICCREATE._serialized_end=464
  _TOPICCLUSTERIZEPARAMS._serialized_start=467
  _TOPICCLUSTERIZEPARAMS._serialized_end=610
  _TOPICFILTERINTERSECT._serialized_start=612
  _TOPICFILTERINTERSECT._serialized_end=720
  _QUERY._serialized_start=722
  _QUERY._serialized_end=744
# @@protoc_insertion_point(module_scope)
