# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mosaico/v1/requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mosaicolabs.proto.v1 import core_pb2 as mosaico_dot_v1_dot_core__pb2
from mosaicolabs.proto.v1 import time_pb2 as mosaico_dot_v1_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19mosaico/v1/requests.proto\x12\x13mosaico.v1.requests\x1a\x15mosaico/v1/core.proto\x1a\x15mosaico/v1/time.proto\"\"\n\x0fResourceLocator\x12\x0f\n\x07locator\x18\x01 \x01(\t\"#\n\x0bSessionUuid\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\"M\n\x12NotificationCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x19\n\x11notification_type\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"8\n\x0eSequenceCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x15\n\ruser_metadata\x18\x02 \x01(\x0c\"\x98\x01\n\x0bTopicCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x14\n\x0csession_uuid\x18\x02 \x01(\t\x12\x35\n\x14serialization_format\x18\x03 \x01(\x0e\x32\x17.mosaico.v1.core.Format\x12\x14\n\x0contology_tag\x18\x04 \x01(\t\x12\x15\n\ruser_metadata\x18\x05 \x01(\x0c\"\x8e\x01\n\x15TopicClusterizeParams\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x18\n\x10\x63lustering_dt_ns\x18\x02 \x01(\x04\x12\x10\n\x08ontology\x18\x03 \x01(\x0c\x12\x38\n\x0ftimestamp_range\x18\x04 \x01(\x0b\x32\x1f.mosaico.v1.time.TimestampRange\"k\n\x14TopicFilterIntersect\x12:\n\x06topics\x18\x01 \x03(\x0b\x32*.mosaico.v1.requests.TopicClusterizeParams\x12\x17\n\x0fintersect_dt_ns\x18\x02 \x01(\x04\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mosaico.v1.requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCELOCATOR._serialized_start=96
  _RESOURCELOCATOR._serialized_end=130
  _SESSIONUUID._serialized_start=132
  _SESSIONUUID._serialized_end=167
  _NOTIFICATIONCREATE._serialized_start=169
  _NOTIFICATIONCREATE._serialized_end=246
  _SEQUENCECREATE._serialized_start=248
  _SEQUENCECREATE._serialized_end=304
  _TOPICCREATE._serialized_start=307
  _TOPICCREATE._serialized_end=459
  _TOPICCLUSTERIZEPARAMS._serialized_start=462
  _TOPICCLUSTERIZEPARAMS._serialized_end=604
  _TOPICFILTERINTERSECT._serialized_start=606
  _TOPICFILTERINTERSECT._serialized_end=713
  _QUERY._serialized_start=715
  _QUERY._serialized_end=737
# @@protoc_insertion_point(module_scope)
