# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mosaico/v1/requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mosaicolabs.proto.v1 import core_pb2 as mosaico_dot_v1_dot_core__pb2
from mosaicolabs.proto.v1 import time_pb2 as mosaico_dot_v1_dot_time__pb2
from mosaicolabs.proto.v1 import query_pb2 as mosaico_dot_v1_dot_query__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19mosaico/v1/requests.proto\x12\x13mosaico.v1.requests\x1a\x15mosaico/v1/core.proto\x1a\x15mosaico/v1/time.proto\x1a\x16mosaico/v1/query.proto\"\"\n\x0fResourceLocator\x12\x0f\n\x07locator\x18\x01 \x01(\t\"#\n\x0bSessionUuid\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\"M\n\x12NotificationCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x19\n\x11notification_type\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"8\n\x0eSequenceCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x15\n\ruser_metadata\x18\x02 \x01(\x0c\"\x98\x01\n\x0bTopicCreate\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x14\n\x0csession_uuid\x18\x02 \x01(\t\x12\x35\n\x14serialization_format\x18\x03 \x01(\x0e\x32\x17.mosaico.v1.core.Format\x12\x14\n\x0contology_tag\x18\x04 \x01(\t\x12\x15\n\ruser_metadata\x18\x05 \x01(\x0c\"\xb0\x01\n\x15TopicClusterizeParams\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x18\n\x10\x63lustering_dt_ns\x18\x02 \x01(\x04\x12\x32\n\x08ontology\x18\x03 \x01(\x0b\x32 .mosaico.v1.query.OntologyFilter\x12\x38\n\x0ftimestamp_range\x18\x04 \x01(\x0b\x32\x1f.mosaico.v1.time.TimestampRange\"k\n\x14TopicFilterIntersect\x12:\n\x06topics\x18\x01 \x03(\x0b\x32*.mosaico.v1.requests.TopicClusterizeParams\x12\x17\n\x0fintersect_dt_ns\x18\x02 \x01(\x04\"1\n\x05Query\x12(\n\x06\x66ilter\x18\x01 \x01(\x0b\x32\x18.mosaico.v1.query.Filterb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mosaico.v1.requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCELOCATOR._serialized_start=120
  _RESOURCELOCATOR._serialized_end=154
  _SESSIONUUID._serialized_start=156
  _SESSIONUUID._serialized_end=191
  _NOTIFICATIONCREATE._serialized_start=193
  _NOTIFICATIONCREATE._serialized_end=270
  _SEQUENCECREATE._serialized_start=272
  _SEQUENCECREATE._serialized_end=328
  _TOPICCREATE._serialized_start=331
  _TOPICCREATE._serialized_end=483
  _TOPICCLUSTERIZEPARAMS._serialized_start=486
  _TOPICCLUSTERIZEPARAMS._serialized_end=662
  _TOPICFILTERINTERSECT._serialized_start=664
  _TOPICFILTERINTERSECT._serialized_end=771
  _QUERY._serialized_start=773
  _QUERY._serialized_end=822
# @@protoc_insertion_point(module_scope)
