# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mosaico/v1/responses.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mosaicolabs.proto.v1 import time_pb2 as mosaico_dot_v1_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amosaico/v1/responses.proto\x12\x14mosaico.v1.responses\x1a\x15mosaico/v1/time.proto\"\x1c\n\x0cResourceUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\".\n\rSessionCreate\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07locator\x18\x02 \x01(\t\"b\n\x10NotificationItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11notification_type\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x18\n\x10\x63reated_datetime\x18\x04 \x01(\t\"Q\n\x10NotificationList\x12=\n\rnotifications\x18\x01 \x03(\x0b\x32&.mosaico.v1.responses.NotificationItem\"7\n\x0eQueryItemTopic\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x14\n\x0contology_tag\x18\x02 \x01(\t\"S\n\tQueryItem\x12\x10\n\x08sequence\x18\x01 \x01(\t\x12\x34\n\x06topics\x18\x02 \x03(\x0b\x32$.mosaico.v1.responses.QueryItemTopic\"7\n\x05Query\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.mosaico.v1.responses.QueryItem\"P\n\x15TopicFilterClusterize\x12+\n\x02ts\x18\x01 \x01(\x0b\x32\x1f.mosaico.v1.time.TimestampRange\x12\n\n\x02id\x18\x02 \x01(\x04\"F\n\nSemVerItem\x12\r\n\x05major\x18\x01 \x01(\x04\x12\r\n\x05minor\x18\x02 \x01(\x04\x12\r\n\x05patch\x18\x03 \x01(\x04\x12\x0b\n\x03pre\x18\x04 \x01(\t\"\x83\x01\n\x0cServerConfig\x12$\n\x1cgrpc_max_decode_message_size\x18\x01 \x01(\x04\x12$\n\x1cgrpc_max_encode_message_size\x18\x02 \x01(\x04\x12\'\n\x1fgrpc_target_encode_message_size\x18\x03 \x01(\x04\"\x83\x01\n\nServerInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x30\n\x06semver\x18\x02 \x01(\x0b\x32 .mosaico.v1.responses.SemVerItem\x12\x32\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\".mosaico.v1.responses.ServerConfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mosaico.v1.responses_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCEUUID._serialized_start=75
  _RESOURCEUUID._serialized_end=103
  _SESSIONCREATE._serialized_start=105
  _SESSIONCREATE._serialized_end=151
  _NOTIFICATIONITEM._serialized_start=153
  _NOTIFICATIONITEM._serialized_end=251
  _NOTIFICATIONLIST._serialized_start=253
  _NOTIFICATIONLIST._serialized_end=334
  _QUERYITEMTOPIC._serialized_start=336
  _QUERYITEMTOPIC._serialized_end=391
  _QUERYITEM._serialized_start=393
  _QUERYITEM._serialized_end=476
  _QUERY._serialized_start=478
  _QUERY._serialized_end=533
  _TOPICFILTERCLUSTERIZE._serialized_start=535
  _TOPICFILTERCLUSTERIZE._serialized_end=615
  _SEMVERITEM._serialized_start=617
  _SEMVERITEM._serialized_end=687
  _SERVERCONFIG._serialized_start=690
  _SERVERCONFIG._serialized_end=821
  _SERVERINFO._serialized_start=824
  _SERVERINFO._serialized_end=955
# @@protoc_insertion_point(module_scope)
