# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mosaico/v1/time.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15mosaico/v1/time.proto\x12\x0fmosaico.v1.time\"T\n\x0eTimestampRange\x12\x15\n\x08start_ns\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x13\n\x06\x65nd_ns\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x0b\n\t_start_nsB\t\n\x07_end_nsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mosaico.v1.time_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMESTAMPRANGE._serialized_start=42
  _TIMESTAMPRANGE._serialized_end=126
# @@protoc_insertion_point(module_scope)
