import json
import math
from pathlib import Path
from typing import Any, Dict, Union

from google.protobuf.message import Message

from mosaicolabs import Time

from .utils.generated.common_pb2 import (
    Header as _Header,
    Quaternion as _Quaternion,
    Stamp as _Stamp,
    Vector3 as _Vector3,
)
from .utils.generated.gps_pb2 import (
    FIX_TYPE_DIFFERENTIAL,
    GeoPoint as _GeoPoint,
    Gps as _Gps,
)
from .utils.generated.imu_pb2 import IMU_STATUS_OK, Imu as _Imu
from .utils.generated.magnetometer_pb2 import (
    AxisReading as _AxisReading,
    Magnetometer as _Magnetometer,
)

IMU_CHANNEL_NAME = "sensor_msg.Imu"
GPS_CHANNEL_NAME = "sensor_msg.Gps"
MAGNETOMETER_CHANNEL_NAME = "sensor_msg.Magnetometer"

ALL_CHANNEL_NAMES = [IMU_CHANNEL_NAME, GPS_CHANNEL_NAME, MAGNETOMETER_CHANNEL_NAME]

# ----- JSON Schema definitions -----
# Loaded verbatim from utils/jsonschema/*.schema.json.
# Only object/properties, array/items and the number/integer/boolean/string scalars are used,
# since that is all mosaicolabs' JsonschemaSchemaConverter understands.

_JSONSCHEMA_DIR = Path(__file__).parent / "utils" / "jsonschema"


def _load_jsonschema(name: str) -> Dict[str, Any]:
    return json.loads((_JSONSCHEMA_DIR / f"{name}.schema.json").read_text())


IMU_JSONSCHEMA = _load_jsonschema("imu")
GPS_JSONSCHEMA = _load_jsonschema("gps")
MAGN_JSONSCHEMA = _load_jsonschema("magnetometer")

# ----- Protobuf schema definitions -----
# Message classes generated by protoc from utils/proto/*.proto into
# utils/generated/*_pb2.py (see utils/README.md). make_*_mcap() constructs real
# protobuf messages with these; mcap_protobuf.writer.Writer (used in conftest.py)
# derives the MCAP schema record (name + FileDescriptorSet bytes) from the message's
# own DESCRIPTOR, so nothing else needs to be exposed here.

IMU_PROTOBUF_MSGTYPE = "mosaicolabs.testing.mcap.Imu"
GPS_PROTOBUF_MSGTYPE = "mosaicolabs.testing.mcap.Gps"
MAGN_PROTOBUF_MSGTYPE = "mosaicolabs.testing.mcap.Magnetometer"


def make_imu_mcap(meas_time: Time, encoding: str) -> Union[Dict[str, Any], Message]:
    t = meas_time.to_float()

    if encoding == "jsonschema":
        return {
            "header": {
                "stamp": {"sec": meas_time.seconds, "nanosec": meas_time.nanoseconds},
                "frame_id": "imu_link",
            },
            "orientation": {"x": math.sin(t), "y": math.cos(t), "z": 0.0, "w": 1.0},
            "angular_velocity": {
                "x": 0.01 * math.sin(t),
                "y": 0.02 * math.cos(t),
                "z": 0.03,
            },
            "linear_acceleration": {
                "x": 0.0,
                "y": 0.0,
                "z": 9.81 + 0.1 * math.sin(t),
            },
            "linear_acceleration_covariance": [
                0.01 if i % 4 == 0 else 0.0 for i in range(9)
            ],
            "status": 0,
            "calibrated": True,
            "sequence": int(t * 1000) % 65536,
            "temperature_millideg": 25000 + int(100 * math.sin(t)),
            "uptime_ns": meas_time.to_nanoseconds(),
            "drift_estimate": 0.001 * math.sin(t),
            "diagnostic_note": f"imu-sample-{meas_time.to_nanoseconds()}",
        }
    elif encoding == "protobuf":
        msg = _Imu(
            header=_Header(
                stamp=_Stamp(sec=meas_time.seconds, nanosec=meas_time.nanoseconds),
                frame_id="imu_link",
            ),
            orientation=_Quaternion(x=math.sin(t), y=math.cos(t), z=0.0, w=1.0),
            angular_velocity=_Vector3(
                x=0.01 * math.sin(t), y=0.02 * math.cos(t), z=0.03
            ),
            linear_acceleration=_Vector3(x=0.0, y=0.0, z=9.81 + 0.1 * math.sin(t)),
            linear_acceleration_covariance=[
                0.01 if i % 4 == 0 else 0.0 for i in range(9)
            ],
            status=IMU_STATUS_OK,
            calibrated=True,
            sequence=int(t * 1000) % 65536,
            temperature_millideg=25000 + int(100 * math.sin(t)),
            uptime_ns=meas_time.to_nanoseconds(),
            drift_estimate=0.001 * math.sin(t),
            raw_diagnostic=f"imu-sample-{meas_time.to_nanoseconds()}".encode(),
        )
        return msg
    else:
        raise Exception(f"Unsupported encoding '{encoding}'")


def make_gps_mcap(meas_time: Time, encoding: str) -> Union[Dict[str, Any], Message]:
    t = meas_time.to_float()

    if encoding == "jsonschema":
        return {
            "header": {
                "stamp": {"sec": meas_time.seconds, "nanosec": meas_time.nanoseconds},
                "frame_id": "gps_link",
            },
            "position": {
                "latitude": 45.070 + 0.0001 * math.sin(t),
                "longitude": 7.686 + 0.0001 * math.cos(t),
                "altitude": 239.0 + math.sin(t),
            },
            "position_covariance": [0.5 if i % 4 == 0 else 0.0 for i in range(9)],
            "fix_type": 3,
            "satellites_visible": 12,
            "satellites_used": 9,
            "differential": True,
            "horizontal_accuracy": 0.02,
            "vertical_accuracy": 0.05,
            "utc_time_micros": meas_time.to_nanoseconds() // 1000,
            "station_id": "BASE-01",
            "active_satellite_ids": ["G01", "G05", "E11"],
        }
    elif encoding == "protobuf":
        msg = _Gps(
            header=_Header(
                stamp=_Stamp(sec=meas_time.seconds, nanosec=meas_time.nanoseconds),
                frame_id="gps_link",
            ),
            position=_GeoPoint(
                latitude=45.070 + 0.0001 * math.sin(t),
                longitude=7.686 + 0.0001 * math.cos(t),
                altitude=239.0 + math.sin(t),
            ),
            position_covariance=[0.5 if i % 4 == 0 else 0.0 for i in range(9)],
            fix_type=FIX_TYPE_DIFFERENTIAL,
            satellites_visible=12,
            satellites_used=9,
            differential=True,
            horizontal_accuracy=0.02,
            vertical_accuracy=0.05,
            utc_time_micros=meas_time.to_nanoseconds() // 1000,
            station_id="BASE-01",
            raw_nmea=f"$GPGGA,{meas_time.to_nanoseconds()}".encode(),
            active_satellite_ids=["G01", "G05", "E11"],
        )
        return msg
    else:
        raise Exception(f"Unsupported encoding '{encoding}'")


def make_magn_mcap(meas_time: Time, encoding: str) -> Union[Dict[str, Any], Message]:
    t = meas_time.to_float()

    readings = [
        {"axis": "x", "value": 20.0 + math.sin(t), "saturated": False},
        {"axis": "y", "value": -5.0 + math.cos(t), "saturated": False},
        {"axis": "z", "value": 42.0, "saturated": t > 2.5},
    ]

    if encoding == "jsonschema":
        return {
            "header": {
                "stamp": {"sec": meas_time.seconds, "nanosec": meas_time.nanoseconds},
                "frame_id": "magn_link",
            },
            "magnetic_field": {
                "x": 20.0 + math.sin(t),
                "y": -5.0 + math.cos(t),
                "z": 42.0,
            },
            "magnetic_field_covariance": [
                0.02 if i % 4 == 0 else 0.0 for i in range(9)
            ],
            "temperature_celsius": 21.5 + 0.1 * math.sin(t),
            "sensor_id": 7,
            "saturated": t > 2.5,
            "calibration_notes": ["factory-cal", "temp-compensated"],
            "readings": readings,
            "hardware_revision": 3,
            "raw_counter": meas_time.to_nanoseconds() % 1_000_000,
        }
    elif encoding == "protobuf":
        msg = _Magnetometer(
            header=_Header(
                stamp=_Stamp(sec=meas_time.seconds, nanosec=meas_time.nanoseconds),
                frame_id="magn_link",
            ),
            magnetic_field=_Vector3(x=20.0 + math.sin(t), y=-5.0 + math.cos(t), z=42.0),
            magnetic_field_covariance=[0.02 if i % 4 == 0 else 0.0 for i in range(9)],
            temperature_celsius=21.5 + 0.1 * math.sin(t),
            sensor_id=7,
            saturated=t > 2.5,
            calibration_notes=["factory-cal", "temp-compensated"],
            readings=[_AxisReading(**reading) for reading in readings],
            hardware_revision=3,
            raw_counter=meas_time.to_nanoseconds() % 1_000_000,
        )
        return msg
    else:
        raise Exception(f"Unsupported encoding '{encoding}'")


# ----- Time generator -----

START_TIME_S = 0
START_TIME_NS = 0
STEP_NS = 5000000  # 5ms
N_STEPS = 1000  # 0 seconds -> 5 seconds


def time_generator(
    start_sec: int,
    start_nanosec: int,
    step_nanosec: int,
    steps: int,
):
    sec = start_sec
    nsec = start_nanosec

    for _ in range(steps):
        yield Time(seconds=sec, nanoseconds=nsec)

        nsec += step_nanosec
        sec += nsec // 1_000_000_000
        nsec = nsec % 1_000_000_000
