name: "mosaico-devel"
services:
  database:
    image: postgres:16
    container_name: db-devel 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mosaico
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  store:
    image: ghcr.io/versity/versitygw:latest
    container_name: store
    ports:
      - "127.0.0.1:7070:7070"  # S3 API
      - "127.0.0.1:7071:7071"  # Admin API
      - "127.0.0.1:8080:8080"  # Web UI
    
    environment:
      ROOT_ACCESS_KEY: admin
      ROOT_SECRET_KEY: password
      VGW_PORT: ":7070"
      VGW_ADMIN_PORT: ":7071"
      VGW_WEBUI_PORT: ":8080"
      VGW_WEBUI_GATEWAYS: "http://127.0.0.1:7070"
      VGW_WEBUI_ADMIN_GATEWAYS: "http://127.0.0.1:7071"
      VGW_BACKEND: posix
      VGW_BACKEND_ARGS: /data/s3
      VGW_HEALTH: "/health"
    volumes:
      - /tmp/versitygw/s3/mosaico:/data/s3/mosaico
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:7070/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

