FROM rust:1.92-slim-bullseye AS builder

WORKDIR /mosaicod

RUN apt-get update && \
  apt-get install -y \
  pkg-config \
  libpq-dev \
  build-essential \
  ca-certificates 

COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
COPY tests ./tests
COPY bin ./bin

RUN SQLX_OFFLINE=true cargo build --bin mosaicod --profile docker

FROM gcr.io/distroless/cc-debian11

WORKDIR /mosaicod

COPY --from=builder /mosaicod/target/docker/mosaicod /usr/local/bin/mosaicod

ENTRYPOINT ["mosaicod"]
