from dataclasses import dataclass
import datetime
from enum import StrEnum
from typing import Any, Dict, Optional

from mosaicolabs.helpers.helpers import unpack_topic_full_path


def _parse_datetime_str(s: str) -> datetime.datetime:
    if s.endswith(" UTC"):
        s = s.replace(" UTC", "+00:00")
        return datetime.datetime.fromisoformat(s)
    else:
        # no timezone → assume UTC
        return datetime.datetime.fromisoformat(s).replace(tzinfo=datetime.timezone.utc)


class NotificationType(StrEnum):
    """
    Classification of platform-level notifications.

    These identifiers distinguish the severity and intent of messages sent from the
    Mosaico server regarding resource states or operation failures.

    Attributes:
        ERROR: Indicates a critical failure during resource operations, such as a
            writing interruption or serialization fault.
    """

    ERROR = "error"
    """Critical error notification."""


@dataclass
class Notification:
    """
    Platform diagnostic notification.

    A `Notification` object represents a specific event or error report stored on the
    platform server. These are typically generated by asynchronous ingestion tasks
    and are critical for debugging failures when using
    [`OnErrorPolicy.Report`][mosaicolabs.enum.OnErrorPolicy].

    ### Discovery
    Notifications can be retrieved at both the sequence and topic level via the
    Mosaico client:

    * [`MosaicoClient.list_sequence_notifications()`][mosaicolabs.comm.MosaicoClient.list_sequence_notifications]
    * [`MosaicoClient.list_topic_notifications()`][mosaicolabs.comm.MosaicoClient.list_topic_notifications]

    Example:
        ```python
        with MosaicoClient.connect("localhost", 6726) as client:
            # Retrieve notifications for a problematic sequence
            errors = client.list_sequence_notifications("mission_alpha")
            for error in errors:
                print(f"[{error.created_datetime}] {error.type}: {error.message}")
        ```

    Attributes:
        sequence_name: The unique identifier of the associated sequence.
        type: The [`NotificationType`][mosaicolabs.comm.notifications.NotificationType]
            categorization of this event.
        message: A detailed string describing the event or error cause.
        created_datetime: The timestamp when the server generated the notification.
        topic_name: Optional; the specific topic name if the notification is
            granular to a single data channel.
    """

    sequence_name: str
    type: NotificationType
    message: str
    created_datetime: datetime.datetime
    topic_name: Optional[str] = None

    @classmethod
    def _from_dict(cls, data: Dict[str, Any]) -> "Notification":
        """
        Create a Notification object from a dictionary.

        Args:
            data: The dictionary to create the Notification object from.

        Returns:
            A Notification object.
        """
        sequence_name = data["name"]
        unpacked = unpack_topic_full_path(sequence_name)
        topic_name = None
        if unpacked is not None:
            sequence_name, topic_name = unpacked

        return cls(
            sequence_name=sequence_name,
            topic_name=topic_name,
            type=NotificationType(data["notification_type"]),
            message=data["msg"],
            created_datetime=_parse_datetime_str(data["created_datetime"]),
        )
