"""
Serialization and Registry Module.

This module defines the `Serializable` base class, which serves as the root for all
specific ontology data types (e.g., IMU, Image, Odometry).

It implements a **Registry/Factory Pattern**:
1.  **Auto-Registration**: Any subclass defined in the code is automatically registered
    via `__pydantic_init_subclass__`.
2.  **Factory Creation**: The `._create()` method instantiates specific subclasses based
    on a string tag.
3.  **Query Capability**: It injects query proxies allowing users to write `IMU.Q.acc_x > 0`.
"""

from enum import Enum
from typing import (
    Annotated,
    Any,
    ClassVar,
    Dict,
    List,
    Optional,
    Type,
    Union,
    get_args,
    get_origin,
)

import pyarrow as pa

from mosaicolabs.enum import SerializationFormat
from mosaicolabs.helpers import camel_to_snake

from .base_model import BaseModel
from .internal.helpers import _fix_empty_dicts
from .internal.pyarrow_mapper import PyarrowFieldMapper
from .query.expressions import _QueryCatalogExpression
from .query.generation.api import _QueryProxyMixin
from .types import BASE_MAPPING

# --- Private Registry ---
# Global dictionary mapping string tags (e.g., "imu") to class types.
_SENSOR_REGISTRY: Dict[str, Type["Serializable"]] = {}


class Serializable(BaseModel, _QueryProxyMixin):
    """
    The base class for all Mosaico ontology data payloads.

    This class serves as the root for every sensor and data type in the Mosaico ecosystem.
    By inheriting from `Serializable`, data models are automatically compatible with the platform's storage,
    querying, and serialization engines.

    ### Dynamic Attributes Injection
    When you define a subclass, several key attributes are automatically managed or required.
    Understanding these is essential for customizing how your data is treated by the platform:

    * **`__serialization_format__`**:
        Determines the batching strategy and storage optimization.
        * **Role**: It tells the `SequenceWriter` whether to flush data based on byte size (optimal for heavy data like `Images`) or record count (optimal for light telemetry like `IMU`).
        * **Default**: `SerializationFormat.Default`.

    * **`__ontology_tag__`**:
        The unique string identifier for the class (e.g., `"imu"`, `"gps_raw"`).
        * **Role**: This tag is used in the global registry to reconstruct objects from raw platform data.
        * **Generation**: If not explicitly provided, it is auto-generated by converting the class name from `CamelCase` to `snake_case`.

    * **`__class_type__`**:
        A reference to the concrete class itself.
        * **Role**: Injected during initialization to facilitate polymorphic instantiation and safe type-checking when extracting data from a [`Message`][mosaicolabs.models.Message].

    ### Requirements for Custom Ontologies
    To create a valid custom ontology, your subclass must:

    1.  Inherit from `Serializable`.
    2.  Define the attributes using [`MosaicoType`][mosaicolabs.models.MosaicoType] and [`MosaicoField`][mosaicolabs.models.types.MosaicoField]

    Tip: Automatic Registration
        Any subclass of `Serializable` is automatically registered in the global Mosaico registry upon definition. This enables the use of the factory methods and the `.Q` query proxy immediately.
    """

    # --- Factory/Metadata Attributes ---

    # Defaults to 'Default' SerializationFormat.
    # Heavy data types (like Images) should override this to 'Image' (Bytes-based batching).
    __serialization_format__: ClassVar[SerializationFormat] = (
        SerializationFormat.Default
    )

    # Unique tag. If None, it is auto-generated from the class name (CamelCase -> snake_case).
    __ontology_tag__: ClassVar[Optional[str]] = None

    # Reference to the actual subclass.
    __class_type__: ClassVar[Type["Serializable"]]

    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs):
        """
        Registers the subclass and injects query capabilities.

        This method is called automatically when a new ontology class is defined.
        It performs schema validation, tag generation, and global registration.

        Raises:
            AttributeError: If `__msco_pyarrow_struct__` is missing or invalid.
            ValueError: If the generated or assigned tag collides with an existing one.
        """
        cls.__msco_pyarrow_struct__ = cls._build_ontology_struct(cls)
        # TODO: check if is it correct call super here.
        super().__pydantic_init_subclass__(**kwargs)

        # Tag Generation
        tag = cls.__ontology_tag__ or camel_to_snake(cls.__name__)
        cls.__ontology_tag__ = tag
        cls.__class_type__ = cls

        # Registration
        if tag in _SENSOR_REGISTRY:
            raise ValueError(
                f"Duplicate ontology tag '{tag}' detected "
                f"(already registered for '{_SENSOR_REGISTRY[tag].__name__}')"
            )
        _SENSOR_REGISTRY[tag] = cls

        # Query Proxy Injection
        # Enables syntax like: MySensor.Q.field_name > value
        _QueryProxyMixin._inject_query_proxy(
            cls,
            mapper=PyarrowFieldMapper(),
            query_expression_type=_QueryCatalogExpression,
            query_prefix=None,
        )

    # --- Factory Methods ---

    @classmethod
    def _create(cls, tag: str, *args, **kwargs) -> "Serializable":
        """
        Factory method to instantiate a specific ontology object by its tag.

        Args:
            tag: The unique ontology identifier (e.g., "imu", "gps").
            *args: Positional arguments for the subclass constructor.
            **kwargs: Keyword arguments for the subclass constructor.

        Returns:
            An instance of the requested `Serializable` subclass.

        Raises:
            ValueError: If the tag is not found in the global registry.
        """
        if tag not in _SENSOR_REGISTRY:
            raise ValueError(
                f"No ontology registered with tag '{tag}'. "
                f"Available tags: {list(_SENSOR_REGISTRY.keys())}"
            )

        # Clean up potential artifacts from Parquet deserialization (e.g., None as empty structs)
        fixed_kwargs = _fix_empty_dicts(kwargs) if kwargs else {}

        # Instantiate
        return _SENSOR_REGISTRY[tag](*args, **fixed_kwargs)

    # --- Registry Helper Methods ---

    @classmethod
    def _list_registered(cls) -> List[str]:
        """Returns a list of all currently registered ontology tags."""
        return list(_SENSOR_REGISTRY.keys())

    @classmethod
    def _is_registered(cls, tag: str) -> bool:
        """
        Checks if a tag is registered.

        Args:
            tag (str): The tag to check.

        Returns:
            bool: True if registered.
        """
        return tag in _SENSOR_REGISTRY.keys()

    @classmethod
    def _get_class_type(cls, tag: str) -> Optional[Type["Serializable"]]:
        """
        Retrieves the concrete Python class type associated with a specific tag.

        Args:
            tag: The unique ontology identifier.

        Returns:
            The Python class type if found, otherwise `None`.
        """
        if not cls._is_registered(tag):
            return None
        return _SENSOR_REGISTRY[tag].__class_type__

    @classmethod
    def _get_ontology_tag(
        cls, class_type_name: str, case_sensitive: bool = True
    ) -> Optional[str]:
        """
        Reverse lookup: finds a tag given a class name.

        Args:
            class_type_name (str): The name of the class (e.g., "IMU").
            case_sensitive (bool): Whether to perform case-sensitive matching.

        Returns:
            Optional[str]: The tag, or None if the class is not found.
        """
        class_type_name_cmp = (
            class_type_name if case_sensitive else class_type_name.lower()
        )

        return next(
            (
                sens.__ontology_tag__
                for sens in _SENSOR_REGISTRY.values()
                if (
                    sens.__class_type__.__name__
                    if case_sensitive
                    else sens.__class_type__.__name__.lower()
                )
                == class_type_name_cmp
            ),
            None,
        )

    @classmethod
    def _build_ontology_struct(cls, model_class: type[BaseModel]) -> pa.StructType:
        """
        Recursively converts a Pydantic model into a PyArrow StructType.

        This method iterates through the fields of a Pydantic model, resolves their
        types into PyArrow equivalents, and preserves field descriptions as
        PyArrow field metadata.

        Args:
            model_class: The Pydantic model class to convert.

        Returns:
            A pa.StructType representing the schema of the Pydantic model.
        """

        cached_struct = model_class.__dict__.get("__msco_pyarrow_struct__")
        if cached_struct and len(cached_struct) > 0:
            return cached_struct

        pa_fields = []
        for field_name, field_info in model_class.model_fields.items():
            annotation = field_info.annotation
            metadata = field_info.metadata[0] if field_info.metadata else None
            pa_type = cls._resolve_type(annotation, metadata)

            # Get the nullable of json_schema_extra if MosaicoField is used otherwise "required" attribute from pydantic
            nullable = (
                bool(
                    field_info.json_schema_extra.get(
                        "nullable", not field_info.is_required()
                    )
                )
                if field_info.json_schema_extra
                else not field_info.is_required()
            )
            metadata = None

            if field_info.description:
                metadata = {b"description": field_info.description.encode("utf-8")}

            pa_fields.append(
                pa.field(field_name, pa_type, nullable=nullable, metadata=metadata)
            )
        return pa.struct(pa_fields)

    @classmethod
    def _resolve_type(
        cls, base_type: Any, suggested_type: Optional[Any] = None
    ) -> pa.DataType:
        """
        Maps Python/Pydantic types to their corresponding PyArrow DataType.

        This method handles nested structures, including:
        * Primitive types (via BASE_MAPPING).
        * Complex types (List, Dict/Map).
        * Pydantic models (nested structs).
        * Enums (resolved to their base primitive type).
        * Unions/Optionals (supports single-type Unions with None).
        * Annotated types (extracts metadata for type hinting).

        Args:
            base_type: The Python type or type hint to resolve.
            suggested_type: An optional pre-defined PyArrow DataType provided
                via Annotated metadata.

        Returns:
            The resolved pa.DataType.

        Raises:
            NotImplementedError: If a Union contains more than one non-None type.
            ValueError: If the type cannot be mapped to a known PyArrow type.
        """
        if isinstance(suggested_type, pa.DataType):
            return suggested_type

        origin = get_origin(base_type)
        args = get_args(base_type)

        if origin is Annotated:
            return cls._resolve_type(args[0], args[1])

        # Optional / Union resolver
        if origin is Union:
            non_none = [a for a in args if a is not type(None)]
            if len(non_none) == 1:
                return cls._resolve_type(non_none[0])
            raise NotImplementedError(
                f"Union with multiple types is not supported: {args}"
            )

        # Dict resolver
        if origin is dict:
            inner_type_1 = args[0] if args else Any
            inner_type_2 = args[1] if args else Any
            resolved_inner_type_1 = cls._resolve_type(inner_type_1)
            resolved_inner_type_2 = cls._resolve_type(inner_type_2)
            return pa.map_(resolved_inner_type_1, resolved_inner_type_2)

        # List resolver
        if origin is list:
            inner_type = args[0] if args else Any
            resolved_inner_type = cls._resolve_type(inner_type)
            return pa.list_(resolved_inner_type)

        # type is a pydantic model
        type_to_check = origin if origin is not None else base_type
        if isinstance(type_to_check, type) and issubclass(type_to_check, BaseModel):
            return cls._build_ontology_struct(type_to_check)

        # fallback
        base_primitive = origin if origin is not None else base_type
        base_pa = BASE_MAPPING.get(base_primitive)

        if base_pa is None:
            # Enum resolver
            if isinstance(base_primitive, type) and issubclass(base_primitive, Enum):
                base_pa = next(
                    (
                        b
                        for b in base_primitive.__mro__
                        if b not in (base_primitive, Enum, object)
                        and not issubclass(b, Enum)
                    ),
                    None,
                )

                return cls._resolve_type(base_pa)
            else:
                raise ValueError(
                    f"{cls.__name__}: Base mapping not found for {base_primitive}. Any is not supported."
                )

        return base_pa

    @classmethod
    def is_registered(cls) -> bool:
        """
        Checks if a class is registered.

        Returns:
            bool: True if registered.
        """
        if not hasattr(cls, "__ontology_tag__"):
            return False
        return cls.__ontology_tag__ in _SENSOR_REGISTRY.keys()

    @classmethod
    def ontology_tag(cls) -> str:
        """
        Retrieves the unique identifier (tag) for the current ontology class, automatically generated during class definition.

        This method provides the string key used by the Mosaico platform to identify and route
        specific data types within the ontology registry. It abstracts
        away the internal naming conventions, ensuring that you always use the correct
        identifier for queries and serialization.

        Returns:
            The registered string tag for this class (e.g., `"imu"`, `"gps"`).

        Raises:
            Exception: If the class was not properly initialized via `__pydantic_init_subclass__`.

        Hint: **Practical Application: Topic Filtering**
            This method is particularly useful when constructing [`QueryTopic`][mosaicolabs.models.query.builders.QueryTopic]
            requests. By using the convenience method [`QueryTopic.with_ontology_tag()`][mosaicolabs.models.query.builders.QueryTopic.with_ontology_tag],
            you can filter topics by data type without hardcoding strings that might change.

            Example:
                ```python
                from mosaicolabs import MosaicoClient, Topic, IMU, QueryTopic

                with MosaicoClient.connect("localhost", 6726) as client:
                    # Filter for a specific data value (using constructor)
                    qresponse = client.query(
                        QueryTopic(
                            Topic.with_ontology_tag(IMU.ontology_tag()),
                        )
                    )

                    # Inspect the response
                    if qresponse is not None:
                        # Results are automatically grouped by Sequence for easier data management
                        for item in qresponse:
                            print(f"Sequence: {item.sequence.name}")
                            print(f"Topics: {[topic.name for topic in item.topics]}")
                ```
        """
        if not hasattr(cls, "__ontology_tag__") or cls.__ontology_tag__ is None:
            raise Exception(
                f"class '{cls.__name__}' has no '__ontology_tag__' attribute. Initialization failed."
            )
        return cls.__ontology_tag__
