use mosaicod_core::{self as core, error::PublicError};
use thiserror::Error;

pub type Result<T> = core::error::PublicResult<T>;

/// Extension trait used to associate gRPC information
/// to a public error.
pub trait PublicErrorGrpcExt {
    /// The gRPC error code associated with the error.
    fn grpc_code(&self) -> tonic::Code;

    /// Sends a log error message
    fn log(&self);

    /// Converts the error into a [`tonic::Status`]
    fn to_status(self) -> tonic::Status;

    /// Log the error and convers to a [`tonic::Status`]
    fn log_to_status(self) -> tonic::Status;
}

/// Implementation of extension trait [`PublicErrorGrpcExt`] for [`PublicError`]
impl<E> PublicErrorGrpcExt for E
where
    E: AsRef<dyn PublicError + Send + Sync>,
{
    fn grpc_code(&self) -> tonic::Code {
        use core::error::ErrorKind;
        use tonic::Code;

        let err = self.as_ref().error();
        match err.kind() {
            ErrorKind::AlreadyExists => Code::AlreadyExists,
            ErrorKind::Unimplemented => Code::Unimplemented,
            ErrorKind::Internal(_) => Code::Internal,
            ErrorKind::BadUuid => Code::InvalidArgument,
            ErrorKind::BadRequest(_) => Code::InvalidArgument,
            ErrorKind::BadHeader(_) => Code::InvalidArgument,
            ErrorKind::NotFound => Code::NotFound,
            ErrorKind::BadLocator => Code::InvalidArgument,
            ErrorKind::Unauthorized => Code::PermissionDenied,
            ErrorKind::Unauthenticated => Code::Unauthenticated,
            ErrorKind::MissingSchema => Code::InvalidArgument,
            ErrorKind::MissingDescriptor => Code::InvalidArgument,
            ErrorKind::MissingApiKey => Code::Unauthenticated,
            ErrorKind::StreamError(_) => Code::Cancelled,
            ErrorKind::MissingHeader => Code::InvalidArgument,
            ErrorKind::LockedTopic(_) => Code::FailedPrecondition,
            ErrorKind::LockedSession(_) => Code::FailedPrecondition,
            ErrorKind::UnlockedTopic(_) => Code::FailedPrecondition,
            ErrorKind::EmptySession(_) => Code::FailedPrecondition,
            ErrorKind::UnsupportedStreamMessage => Code::Aborted,
            ErrorKind::UnsupportedLocator => Code::InvalidArgument,
            ErrorKind::UnsupportedOperation => Code::InvalidArgument,
            ErrorKind::UnsupportedDescriptor => Code::InvalidArgument,
            ErrorKind::UnsupportedSchema(_) => Code::InvalidArgument,
            ErrorKind::InvalidConfiguration(_) => Code::Unknown,
            ErrorKind::UnsupportedTime(_) => Code::InvalidArgument,
        }
    }

    fn log(&self) {
        tracing::error!(
            user_error = self.as_ref().error().to_string(),
            grpc_code = self.grpc_code() as u8,
            internal_error = format!("{:?}", self.as_ref()),
        );
    }

    fn to_status(self) -> tonic::Status {
        tonic::Status::new(self.grpc_code(), self.as_ref().to_string())
    }

    fn log_to_status(self) -> tonic::Status {
        self.log();
        self.to_status()
    }
}

pub trait ToStatusExt<T> {
    /// Logs the result error and converts to a [`tonic::Status`]
    fn log_to_status(self) -> std::result::Result<T, tonic::Status>;
    /// Convert the result error into a [`tonic::Status`]
    fn to_status(self) -> std::result::Result<T, tonic::Status>;
}

impl<T, E> ToStatusExt<T> for std::result::Result<T, E>
where
    E: PublicErrorGrpcExt + Send + Sync,
{
    fn to_status(self) -> std::result::Result<T, tonic::Status> {
        self.map_err(|e| e.to_status())
    }

    fn log_to_status(self) -> std::result::Result<T, tonic::Status> {
        self.inspect_err(|e| e.log()).map_err(|e| e.to_status())
    }
}

/// Used to represent errors generated by mosaicod flight server
#[derive(Error, Debug, Clone)]
pub enum ErrorKind {
    #[error("invalid uuid")]
    InvalidUuid(String),
    #[error("invalid notification type")]
    InvalidNotificationType(String),
    #[error("semaphore closed")]
    SemaphoreClosed,
    #[error("not a semver")]
    NotASemVer(String),
}

#[derive(Debug, Clone)]
pub struct Error(ErrorKind);

impl Error {
    pub fn invalid_uuid(uuid: &str) -> Self {
        Self(ErrorKind::InvalidUuid(uuid.to_string()))
    }

    pub fn invalid_notification_type(ntype: &str) -> Self {
        Self(ErrorKind::InvalidNotificationType(ntype.to_string()))
    }

    pub fn semaphore_closed() -> Self {
        Self(ErrorKind::SemaphoreClosed)
    }

    pub fn not_a_semver(msg: String) -> Error {
        Self(ErrorKind::NotASemVer(msg))
    }
}

impl core::error::PublicError for Error {
    fn error(&self) -> core::Error {
        match &self.0 {
            ErrorKind::InvalidUuid(uuid) => {
                core::Error::bad_request(format!("invalid uuid {uuid}"))
            }
            ErrorKind::InvalidNotificationType(ntype) => {
                core::Error::bad_request(format!("invalid notification type `{ntype}`"))
            }
            ErrorKind::SemaphoreClosed | ErrorKind::NotASemVer(_) => core::Error::internal(None),
        }
    }
}
