use thiserror::Error;

/// A trait for defining structured gRPC error responses.
///
/// Allowing the transformation of internal mosaicod errors into standardized
/// client-facing errors, serving as an abstraction layer to avoid leaking
/// sensitive or internal system details.
pub trait GrpcPublicError: std::fmt::Display + std::fmt::Debug + std::error::Error {
    /// The message that will be sent
    fn public_message(&self) -> String {
        "internal error".to_owned()
    }

    /// The gRPC error code associated with the error.
    fn grpc_code(&self) -> tonic::Code {
        tonic::Code::Internal
    }

    /// Optionally a documentation link can be provided.
    fn documentation_link(&self) -> Option<url::Url> {
        None
    }

    /// Format the error to a client readable string.
    fn to_client_string(&self) -> String {
        let mut client_string = format!(
            "Error: {public_message}",
            public_message = self.public_message()
        );

        // Ensure that the line ends with a `.`
        if !client_string.ends_with('.') {
            client_string.push('.');
        }

        if let Some(link) = self.documentation_link() {
            client_string.push_str(&format!("See {link} for more details."));
        }

        client_string
    }

    /// Sends a log error message
    fn log(&self) {
        tracing::error!(
            user_error = self.public_message(),
            grpc_code = self.grpc_code() as u8,
            internal_error = format!("{:?}", self),
        );
    }

    fn to_status(&self) -> tonic::Status {
        tonic::Status::new(self.grpc_code(), self.to_client_string())
    }
}

pub type BoxGrpcPublicError = Box<dyn GrpcPublicError + Send + Sync + 'static>;

pub type Result<T> = std::result::Result<T, BoxGrpcPublicError>;

/// Blanket implementation
/// Used to automatically box an error with .into()
impl<E> From<E> for Box<dyn GrpcPublicError + Send + Sync>
where
    E: GrpcPublicError + Send + Sync + 'static,
{
    fn from(error: E) -> Self {
        Box::new(error)
    }
}

/// Automatic mapping from [`GrpcPublicError`] to [`tonic::Status`]
impl From<Box<dyn GrpcPublicError + Sync + Send>> for tonic::Status {
    fn from(value: Box<dyn GrpcPublicError + Sync + Send>) -> Self {
        value.to_status()
    }
}

/// Used to represent errors generated by mosaicod flight server
#[derive(Error, Debug)]
pub enum MosaicodFlightError {
    #[error("unauthorized")]
    Unauthorized,
    #[error("unimplemented")]
    Unimplemented,
    #[error("unsupported {0}")]
    Unsupported(String),
    #[error("invalid {0}")]
    Invalid(String),
    #[error("locked")]
    Locked,
    #[error("stream interrupted: {0}")]
    StreamInterrupted(String),
    #[error("missing {0}")]
    Missing(String),
    #[error("internal")]
    Internal(String),
}

impl MosaicodFlightError {
    pub fn unauthorized() -> Self {
        Self::Unauthorized
    }

    pub fn internal(msg: &str) -> Self {
        Self::Internal(msg.to_owned())
    }

    pub fn stream_interrupted(msg: &str) -> Self {
        Self::StreamInterrupted(msg.to_owned())
    }

    pub fn invalid_uuid(uuid: &str) -> Self {
        Self::Invalid(format!("uuid {uuid}"))
    }

    pub fn invalid_notification_type(msg: &str) -> Self {
        Self::Invalid(format!("notification type {msg}"))
    }

    pub fn missing_header() -> Self {
        Self::Missing("header".to_owned())
    }

    pub fn missing_data() -> Self {
        Self::Missing("data".to_owned())
    }

    pub fn missing_api_key_token() -> Self {
        Self::Missing("api key token".to_owned())
    }

    pub fn unsupported_descriptor() -> Self {
        Self::Unsupported("descriptor".to_owned())
    }

    pub fn unsupported_message() -> Self {
        Self::Unsupported("message".to_owned())
    }

    pub fn missing_schema() -> Self {
        Self::Missing("schema".to_owned())
    }

    pub fn missing_descriptor() -> Self {
        Self::Missing("descriptor".to_owned())
    }
}

impl GrpcPublicError for MosaicodFlightError {
    fn public_message(&self) -> String {
        self.to_string()
    }

    fn grpc_code(&self) -> tonic::Code {
        match self {
            Self::Unauthorized => tonic::Code::Unauthenticated,
            Self::Unimplemented => tonic::Code::Unimplemented,
            Self::Unsupported(_) => tonic::Code::Unimplemented,
            Self::Invalid(_) => tonic::Code::InvalidArgument,
            Self::Locked => tonic::Code::PermissionDenied,
            Self::Missing(_) => tonic::Code::InvalidArgument,
            Self::StreamInterrupted(_) => tonic::Code::Cancelled,
            Self::Internal(_) => tonic::Code::Internal,
        }
    }
}

impl GrpcPublicError for mosaicod_marshal::Error {
    fn public_message(&self) -> String {
        self.to_string()
    }

    fn grpc_code(&self) -> tonic::Code {
        tonic::Code::InvalidArgument
    }
}

impl GrpcPublicError for mosaicod_facade::Error {
    fn public_message(&self) -> String {
        match self {
            Self::NotFound(_)
            | Self::Unauthorized
            | Self::Unimplemented
            | Self::SessionLocked
            | Self::TopicLocked
            | Self::TopicUnlocked
            | Self::SessionEmpty
            | Self::TopicAlreadyExists(_) => self.to_string(),
            _ => "internal error".to_owned(),
        }
    }

    fn grpc_code(&self) -> tonic::Code {
        match self {
            Self::NotFound(_) => tonic::Code::NotFound,
            Self::Unauthorized => tonic::Code::Unauthenticated,
            Self::Unimplemented => tonic::Code::Unimplemented,
            Self::TopicAlreadyExists(_) => tonic::Code::AlreadyExists,
            Self::SessionLocked | Self::TopicLocked | Self::TopicUnlocked | Self::SessionEmpty => {
                tonic::Code::FailedPrecondition
            }
            _ => tonic::Code::Internal,
        }
    }
}

impl GrpcPublicError for mosaicod_db::Error {
    fn public_message(&self) -> String {
        "internal database error".to_owned()
    }
}

impl GrpcPublicError for mosaicod_marshal::ActionError {
    fn public_message(&self) -> String {
        match self {
            Self::ResponseSerializationError(_) => "internal error".to_owned(),
            _ => self.to_string(),
        }
    }

    fn grpc_code(&self) -> tonic::Code {
        match self {
            Self::MissingAction(_) => tonic::Code::InvalidArgument,
            Self::BodyDeserializationError(_) => tonic::Code::InvalidArgument,
            Self::ResponseSerializationError(_) => tonic::Code::Internal,
        }
    }
}

impl GrpcPublicError for mosaicod_query::Error {
    fn public_message(&self) -> String {
        match self {
            Self::DeserializationError(_) => self.to_string(),
            _ => "internal error".to_owned(),
        }
    }

    fn grpc_code(&self) -> tonic::Code {
        match self {
            Self::DeserializationError(_) => tonic::Code::InvalidArgument,
            _ => tonic::Code::Internal,
        }
    }
}

impl GrpcPublicError for mosaicod_ext::arrow::SchemaError {
    fn public_message(&self) -> String {
        self.to_string()
    }

    fn grpc_code(&self) -> tonic::Code {
        tonic::Code::InvalidArgument
    }
}

impl GrpcPublicError for mosaicod_core::types::ApiKeyError {
    fn public_message(&self) -> String {
        match self {
            Self::InvalidIntToPermissionCast => "internal error".to_owned(),
            _ => self.to_string(),
        }
    }

    fn grpc_code(&self) -> tonic::Code {
        match self {
            Self::InvalidIntToPermissionCast => tonic::Code::Internal,
            _ => tonic::Code::InvalidArgument,
        }
    }
}

// All errors down here will be mapped to internal error

impl GrpcPublicError for arrow::error::ArrowError {}
impl GrpcPublicError for mosaicod_core::types::ResourceError {}
impl GrpcPublicError for mosaicod_rw::Error {}
