use mosaicod_core::{self as core, error::PublicError};
use thiserror::Error;

pub type Result<T> = core::error::PublicResult<T>;

/// Extension trait used to associate gRPC information
/// to a public error.
pub trait PublicErrorGrpcExt {
    /// The gRPC error code associated with the error.
    fn grpc_code(&self) -> tonic::Code;

    /// Sends a log error message
    fn log(&self);

    /// Converts the error into a [`tonic::Status`]
    fn to_status(self) -> tonic::Status;

    /// Log the error and convers to a [`tonic::Status`]
    fn log_to_status(self) -> tonic::Status;
}

/// Implementation of extension trait [`PublicErrorGrpcExt`] for [`PublicError`]
impl<E> PublicErrorGrpcExt for E
where
    E: AsRef<dyn PublicError + Send + Sync>,
{
    fn grpc_code(&self) -> tonic::Code {
        use core::error::Error;
        use tonic::Code;

        let code = self.as_ref().error();
        match code {
            Error::AlreadyExists => Code::AlreadyExists,
            Error::Unimplemented => Code::Unimplemented,
            Error::Internal => Code::Internal,
            Error::BadUuid => Code::InvalidArgument,
            Error::BadRequest(_) => Code::InvalidArgument,
            Error::BadHeader(_) => Code::InvalidArgument,
            Error::NotFound => Code::NotFound,
            Error::BadLocator => Code::InvalidArgument,
            Error::Unauthorized => Code::PermissionDenied,
            Error::Unauthenticated => Code::Unauthenticated,
            Error::MissingSchema => Code::InvalidArgument,
            Error::MissingDescriptor => Code::InvalidArgument,
            Error::MissingApiKey => Code::Unauthenticated,
            Error::StreamError(_) => Code::Cancelled,
            Error::MissingHeader => Code::InvalidArgument,
            Error::LockedTopic(_) => Code::FailedPrecondition,
            Error::LockedSession(_) => Code::FailedPrecondition,
            Error::UnlockedTopic(_) => Code::FailedPrecondition,
            Error::UnsupportedStreamMessage => Code::Aborted,
            Error::UnsupportedLocator => Code::InvalidArgument,
            Error::UnsupportedOperation => Code::InvalidArgument,
            Error::UnsupportedDescriptor => Code::InvalidArgument,
            Error::UnsupportedSchema(_) => Code::InvalidArgument,
        }
    }

    fn log(&self) {
        tracing::error!(
            user_error = self.as_ref().error_string(),
            grpc_code = self.grpc_code() as u8,
            internal_error = format!("{:?}", self.as_ref()),
        );
    }

    fn to_status(self) -> tonic::Status {
        tonic::Status::new(self.grpc_code(), self.as_ref().to_string())
    }

    fn log_to_status(self) -> tonic::Status {
        self.log();
        self.to_status()
    }
}

pub trait ToStatusExt<T> {
    /// Logs the result error and converts to a [`tonic::Status`]
    fn log_to_status(self) -> std::result::Result<T, tonic::Status>;
    /// Convert the result error into a [`tonic::Status`]
    fn to_status(self) -> std::result::Result<T, tonic::Status>;
}

impl<T, E> ToStatusExt<T> for std::result::Result<T, E>
where
    E: PublicErrorGrpcExt + Send + Sync,
{
    fn to_status(self) -> std::result::Result<T, tonic::Status> {
        self.map_err(|e| e.to_status())
    }

    fn log_to_status(self) -> std::result::Result<T, tonic::Status> {
        self.inspect_err(|e| e.log()).map_err(|e| e.to_status())
    }
}

/// Used to represent errors generated by mosaicod flight server
#[derive(Error, Debug)]
pub enum Error {
    #[error("invalid uuid")]
    InvalidUuid(String),
    #[error("invalid notification type")]
    InvalidNotificationType(String),
    #[error("semaphore closed")]
    SemaphoreClosed,
    #[error("not a semver")]
    NotASemVer(String),
}

pub fn invalid_uuid(uuid: &str) -> Error {
    Error::InvalidUuid(uuid.to_string())
}

pub fn invalid_notification_type(ntype: &str) -> Error {
    Error::InvalidNotificationType(ntype.to_string())
}

pub fn semaphore_closed() -> Error {
    Error::SemaphoreClosed
}

pub fn not_a_semver(msg: String) -> Error {
    Error::NotASemVer(msg)
}

impl core::error::PublicError for Error {
    fn error(&self) -> core::Error {
        match self {
            Self::InvalidUuid(uuid) => core::Error::bad_request(format!("invalid uuid {uuid}")),
            Self::InvalidNotificationType(ntype) => {
                core::Error::bad_request(format!("invalid notification type `{ntype}`"))
            }
            Self::SemaphoreClosed | Self::NotASemVer(_) => core::Error::internal(),
        }
    }
}
