from dataclasses import dataclass

from mosaicolabs.proto.v1 import responses_pb2, time_pb2


@dataclass
class TimestampRange:
    """
    Represents a temporal window defined by a start and end timestamp.

    This utility class is used to define the bounds of sensor data or sequences
    within the Mosaico archive.

    Attributes:
        start (int): The beginning of the range (inclusive), typically in nanoseconds.
        end (int): The end of the range (inclusive), typically in nanoseconds.
    """

    start: int
    end: int

    @classmethod
    def _from_proto(cls, msg: time_pb2.TimestampRange) -> "TimestampRange":
        return cls(start=msg.start_ns, end=msg.end_ns)

    def to_proto(self) -> time_pb2.TimestampRange:
        return time_pb2.TimestampRange(start_ns=self.start, end_ns=self.end)


@dataclass
class TopicCluster:
    """
    A `TopicCluster` object represents a time interval where something relevant happened.
    These are typically generated by asking the backend Topic Filter Clusterize or Topic Filter Intersect actions.

    Attributes:
        id (int): The cluster index if multiple clustyers are returned for the same topic.
        timerange (TimestampRange): The interval that the cluster identifies.
    """

    id: int
    timerange: TimestampRange

    @classmethod
    def _from_proto(cls, msg: responses_pb2.TopicFilterClusterize) -> "TopicCluster":
        """
        Creates a TopicCluster object from a decoded protobuf message.

        Args:
            msg (responses_pb2.TopicFilterClusterize): The decoded cluster message.

        Returns:
            TopicCluster: A TopicCluster object.
        """

        return cls(
            id=msg.id,
            timerange=TimestampRange._from_proto(msg.ts),
        )

    def __str__(self) -> str:
        return f"(id={self.id}, start={self.timerange.start}, end={self.timerange.end})"
