[package]
name = "mosaicod-task"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "mosaicod_task"

[dependencies]
mosaicod-core = { workspace = true }
mosaicod-db = { workspace = true, features = ["postgres"] }
mosaicod-store = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
mosaicod-db = { workspace = true, features = ["postgres", "testing"] }
mosaicod-store = { workspace = true, features = ["testing"] }
sqlx = { workspace = true }
rand = { workspace = true }
filetime = { workspace = true }
