#!/usr/bin/env bash

# Run a development enviroment DB + mosaicod for local testing

# Directory contianing the source code for the SDK
PYTHON_SDK_DIR="mosaico-sdk-py"
# Directory containing the mosaicod source code
MOSAICOD_DIR="mosaicod"
# Directory containing the docker compose.yml file for setup the test infra
DOCKER_DIR="docker/testing"
# This directory will be used to configure mosaicod store and will be deleted at the end of the process
TEST_DIRECTORY="/tmp/__mosaico_dev_env__"
# Log level for mosaicod
RUST_LOG=mosaico=trace
# Database URL (see docker compose if you need to change the params)
MOSAICOD_DB_URL="postgresql://postgres:password@localhost:6543/mosaico"

# This flag should be always `true`, otherwise a running database with live migration
# is required to compile the code (and also we need to reinstall sqlx at each run).
SQLX_OFFLINE=true

# Specifies if the server should start with api key management enabled. If this option is set to true
# a default API key will be generated. Use --api-key option to enable this from command line.
ENABLE_API_KEY=false

# Specifies if the server should start with TLS enabled. If this option is set to true 
# the server will be configured with certificates from `mosaicod/tests/data` folder.
ENABLE_TLS=false

FILE_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$(readlink -f "${FILE_DIR}/..")
DATABASE_URL="${MOSAICOD_DB_URL}"
MOSAICOD_PATH="${PROJECT_DIR}/${MOSAICOD_DIR}"
PYTHON_SDK_PATH="${PROJECT_DIR}/${PYTHON_SDK_DIR}"
DOCKER_PATH="${PROJECT_DIR}/${DOCKER_DIR}"

export DATABASE_URL
export RUST_LOG
export SQLX_OFFLINE
export MOSAICOD_DB_URL
export RUST_BACKTRACE


COLS=$(tput cols || echo 80 )
if (( "$COLS" < 70 )); then
    COLS=70
fi

RED=$(tput setaf 208)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
RESET=$(tput sgr0)
BOLD=$(tput bold)
DIM=$(tput dim)

show_help() {
    cat << EOF
Mosaico disposable development environment.

This script generates a disposable development environment without data. 
It is particularly useful for performing repeatable tests during development.

Usage: dev_env.sh [OPTIONS]

Options:
    -p, --profile               Compile mosaicod with a specific profile.
    --api-key                   Start mosaicod with API key management and generate an admin
                                key.
    --tls                       Start mosaicod with TLS configured. Certificates can be found in 
                                `mosaicod/tests/data` folder.
    --help                      Show this help message
EOF
}

error_handler() {
    echo "${RED}${BOLD}Ops, an error occurred. ${RESET}"
    exit 1
}

trap error_handler ERR

title() {
    local text="$1"
    local char="${2:-#}"
    local color="${3:-${MAGENTA}}"

    local style_col="${BOLD}"
    local padding=$(( (COLS - ${#text} - 2) / 2 ))
    local line

    # Build line of padding characters
    printf -v line "%*s" "$COLS" ""
    line=${line// /$char} 

    # Print the title
    printf "%s%s%.*s %s %.*s%s\n" \
        "$color" "$style_col" \
        "$padding" "$line" "$text" "$padding" "$line" "${RESET}"
}

function cleanup() {
    if [ -n "$MOSAICOD_PID" ]; then
        kill "$MOSAICOD_PID" 2>/dev/null
        wait "$MOSAICOD_PID" 2>/dev/null
        echo "${DIM}mosaicod ($MOSAICOD_PID) terminated.${RESET}"
    fi
    
    rm -r ${TEST_DIRECTORY} 2> /dev/null

    cd ${PROJECT_DIR}/docker/testing
    docker compose down -v 2> /dev/null
}

trap cleanup EXIT

main() {

    MOSAICOD_OPTS=""
    MOSAICOD_BUILD_PROFILE="dev"
    MOSAICOD_BUILD_TARGET="debug"

    while [ $# -gt 0 ]; do
        case "$1" in 
            --profile|-p)
                MOSAICOD_BUILD_PROFILE="$2"
                MOSAICOD_BUILD_TARGET="${MOSAICOD_BUILD_PROFILE}"
                shift 2
                ;;
            --api-key)
                ENABLE_API_KEY=true
                MOSAICOD_OPTS="$MOSAICOD_OPTS --api-key"
                shift
                ;;
            --tls)
                ENABLE_TLS=true
                MOSAICOD_OPTS="$MOSAICOD_OPTS --tls"
                export MOSAICOD_TLS_CERT_FILE="${MOSAICOD_PATH}/tests/data/cert.pem"
                export MOSAICOD_TLS_PRIVATE_KEY_FILE="${MOSAICOD_PATH}/tests/data/key.pem"
                shift
                ;;
            --help|-h)
                show_help
                exit 0
                ;;
            *)
                echo "${RED}Unknown option: $1${RESET}"
                show_help
                exit 1
                ;;
        esac
    done

    mkdir -p "${TEST_DIRECTORY}"

    title "development environment" "#" ${GREEN}

    title "setup" "-"
    echo " * MOSAICOD_DB_URL ${DIM}${MOSAICOD_DB_URL}${RESET}"
    echo " * DATABASE_URL    ${DIM}${DATABASE_URL}${RESET}"
    echo " * SQLX_OFFLINE    ${DIM}${SQLX_OFFLINE}${RESET}"
    cd ${DOCKER_PATH}
    title "docker" "." ${BLUE}
    docker compose up -d --wait 2> /dev/null
    echo "Started ${BOLD}docker/testing${RESET} compose file"

    title "mosaicod" "-"
    cd ${MOSAICOD_PATH}
    title "build" "." ${BLUE}
    cargo build --profile "$MOSAICOD_BUILD_PROFILE" --bin mosaicod

    if $ENABLE_API_KEY; then
        API_KEY=$(RUST_LOG="" ./target/debug/mosaicod api-key create -p manage)

cat << EOF 
    ##################################################################
    #                                                                #
    #                        API KEY MANAGEMENT                      #
    #                                                                #
    #----------------------------------------------------------------#
    #                                                                #
    #  API KEY ${DIM}${API_KEY}${RESET}
    #                                                                #
    ##################################################################
EOF
    fi

    if $ENABLE_TLS; then
cat << EOF
    ##################################################################
    #                                                                #
    #                           TLS ENABLED                          #
    #----------------------------------------------------------------#
    #           Certificate for client can be found at               # 
    #           `mosaicod/tests/data/ca.pem`                         #
    #                                                                #
    ##################################################################
EOF
    fi

    title "running" "." ${BLUE}
    "./target/$MOSAICOD_BUILD_TARGET/mosaicod" run \
      --port 6276 --local-store "$TEST_DIRECTORY" ${MOSAICOD_OPTS}

    MOSAICOD_PID=$!

    title "done" "#" ${GREEN}
}


main "$@"

