[workspace]
members = ["crates/*", "bin/*", "tests/"]
resolver = "3"

[workspace.package]
version = "0.8.0-dev"
authors = ["Mosaico Labs <info@mosaico.dev>"]
homepage = "https://mosaico.dev"
repository = "https://github.com/mosaico-labs/mosaico"
license = "Apache-2.0"
edition = "2024"
rust-version = "1.92"

[workspace.dependencies]
# Internal crates
mosaicod-build = { path = "crates/mosaicod-build" }
mosaicod-commands = { path = "crates/mosaicod-commands" }
mosaicod-config = { path = "crates/mosaicod-config" }
mosaicod-core = { path = "crates/mosaicod-core" }
mosaicod-db = { path = "crates/mosaicod-db" }
mosaicod-facade = { path = "crates/mosaicod-facade" }
mosaicod-ext = { path = "crates/mosaicod-ext" }
mosaicod-marshal = { path = "crates/mosaicod-marshal" }
mosaicod-query = { path = "crates/mosaicod-query" }
mosaicod-rw = { path = "crates/mosaicod-rw" }
mosaicod-grpc = { path = "crates/mosaicod-grpc" }
mosaicod-grpc-flight = { path = "crates/mosaicod-grpc-flight" }
mosaicod-grpc-common = { path = "crates/mosaicod-grpc-common" }
mosaicod-instance-registry = { path = "crates/mosaicod-instance-registry" }
mosaicod-os = { path = "crates/mosaicod-os" }
mosaicod-store = { path = "crates/mosaicod-store" }
mosaicod-task = { path = "crates/mosaicod-task" }

# Arrow stack dependencies
arrow = { version = "58.1.0", default-features = false, features = ["prettyprint", "ipc_compression"] }
arrow-cast = { version = "58.1.0", default-features = false }
arrow-flight = { version = "58.1.0", default-features = false }
arrow-schema = { version = "58.1.0", default-features = false }
parquet = { version = "58.1.0", default-features = false, features = ["arrow", "async", "object_store", "zstd", "simdutf8"] }
datafusion = { version = "54.0.0", default-features = false, features = ["parquet", "sql", "recursive_protection", "nested_expressions"] }
tonic = { version = "0.14.6", default-features = false, features = ["router", "transport", "codegen", "tls-ring", "gzip"] }
object_store = { version = "0.13.2", default-features = false, features = ["aws", "fs"] }

base64 = { version = "0.22.1", default-features = false }
bincode = { version = "2.0.1", default-features = false, features = ["alloc", "derive", "serde"] }
bytes = { version = "1.11.1", default-features = false }
chrono = { version = "0.4.44", default-features = false, features = ["clock"] }
clap = { version = "4.6.1", default-features = false, features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive"] }
colored = { version = "3.1.1", default-features = false }
dotenv = { version = "0.15.0", default-features = false }
etcetera = { version = "0.11.0", default-features = false }
futures = { version = "0.3.32", default-features = false, features = ["async-await"] }
hostname = { version = "0.4.1", default-features = false }
if-addrs = { version = "0.15.0", default-features = false }
mimalloc = { version = "0.1", default-features = false }
rand = { version = "0.10.2", default-features = false, features = ["thread_rng"] }
fastrand = { version = "2.4.1", default-features = false, features = ["alloc"] }
serde = { version = "1.0.228", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.149", default-features = false, features = ["alloc"] }
signal-hook = { version = "0.4.4", default-features = false, features = ["iterator"] }
sqlx = { version = "0.8.6", default-features = false, features = [
    "postgres",
    "macros",
    "runtime-tokio",
    "uuid",
    "json",
    "migrate",
] }
thiserror = { version = "2.0.18", default-features = false }
tokio = { version = "1.50.0", default-features = false, features = ["rt-multi-thread"] }
tokio-util = { version = "0.7", default-features = false }
tokio-stream = { version = "0.1", default-features = false }
url = { version = "2.5.8", default-features = false }
uuid = { version = "1.23.2", default-features = false, features = ["v4"] }
ulid = { version = "1.2.1", default-features = false, features = ["std"] }
crc32fast = { version = "1.5.0", default-features = false }
iso8601 = { version = "0.6.3", default-features = false }
semver = { version = "1.0.28", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["fmt", "ansi", "tracing-log", "json", "env-filter"] }
regex = { version = "1.12.4", default-features = false, features = ["perf", "unicode"] }

# Used for testing
filetime = { version = "0.2.27", default-features = false }

# Used to implement middlewares in mosaicod-server crate
tower = { version = "0.5.3", default-features = false }
http = { version = "1.4.0", default-features = false }

[profile.release]
strip = true    # Strip symbols from binary
panic = "abort" # Smaller binary, no unwinding

[profile.profiling]
inherits = "release"
strip = "none"
panic = "unwind"
debug = true

[profile.optimized]
inherits = "release"
lto = true           # Link-Time Optimization
codegen-units = 1    # Better optimization (slower compile)

[profile.docker]
inherits = "release"
lto = "thin"
opt-level = "s"
