[package]
name = "mosaicod-grpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "mosaicod_grpc"

[dependencies]
mosaicod-grpc-common = { workspace = true }
mosaicod-grpc-flight = { workspace = true }
mosaicod-core = { workspace = true }
mosaicod-db = { workspace = true }
mosaicod-store = { workspace = true }
mosaicod-ext = { workspace = true }
mosaicod-task = { workspace = true }

arrow-flight = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mosaicod-store = { workspace = true, features = ["testing"] }
mosaicod-db = { workspace = true, features = ["testing"] }
sqlx = { workspace = true }
